### ISSUE TITLE
Feedback Cadastro de Historias de Usuário no Github IT3

### ISSUE THREAD

**Issue by joismar** [EmersonVictor/como-e-que-e#138]
Opa! O item foi avaliado com os seguintes critérios:

- Uso de label: Ok
- 1 issue por participante: Não (-3)
- Descrição da issue: Ok

Nota Final: **7**

Qualquer dúvida, estou disponível no Telegram.

**Comment by EmersonVictor** [comment]
@joismar Como assim 1 issue por participante?

**Comment by joismar** [comment]
Dúvida já respondida a José Neto pelo Telegram ;)
