### ISSUE TITLE
Feedback PostMortem IT1

### ISSUE THREAD

**Issue by lsca** [EmersonVictor/como-e-que-e#97]
Eaew Galera, tudo certinho?

Não achei o postmortem de vocês no ultimo [commit](https://github.com/EmersonVictor/como-e-que-e/tree/09f5c886eaf34aa0972e1151642de559b681c4dc) da IT1(8 de outubro).

Por isso dei Zero, se tiverem colocado e eu não achei a pasta avisem aqui. Caso contrario só fechar a issue.

Att,

**Comment by EmersonVictor** [comment]
@lsca Nossos postmortem estão na wiki do GitHub
